nodeLinker: node-modules

packageExtensions:
  "@mui/styled-engine@*":
    dependencies:
      "@emotion/react": ^11.7.1
      "@emotion/styled": ^11.3.0
  "@nrwl/workspace@*":
    dependencies:
      "@angular-devkit/schematics": ^13.3.0
  "@pulumi/pulumi@*":
    peerDependencies:
      dockerode: "*"
  "@remirror/core-utils@*":
    dependencies:
      "@remirror/pm": "*"
  "@remirror/extension-events@*":
    dependencies:
      "@remirror/pm": "*"
  "@remirror/extension-gap-cursor@*":
    dependencies:
      "@remirror/pm": "*"
  "@remirror/extension-yjs@*":
    dependencies:
      prosemirror-model: ^1.14.2
      prosemirror-state: ^1.3.4
      prosemirror-view: ^1.18.8
  "@remirror/react-renderer@*":
    dependencies:
      "@remirror/pm": "*"
  "@remirror/react-utils@*":
    dependencies:
      "@remirror/pm": "*"
  "@remirror/react@*":
    dependencies:
      "@remirror/pm": "*"
  "@remirror/theme@*":
    dependencies:
      "@remirror/pm": "*"
  "@storybook/preset-create-react-app@*":
    dependencies:
      webpack-hot-middleware: "*"
  babel-preset-react-app@*:
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": "*"
  dotenv@*:
    dependencies:
      "@types/node": 14.17.9
  grant@*:
    dependencies:
      "@hapi/hapi": "*"
      express: "*"
      koa: "*"
  graphile-build-pg@^4.5.0:
    dependencies:
      graphql: ">=0.9 <0.14 || ^14.0.2"
      pg: "*"
  graphile-build@^4.5.0:
    dependencies:
      graphql: ">=0.9 <0.14 || ^14.0.2"
  graphile-utils@*:
    dependencies:
      graphile-build-pg: "*"
  jest-jasmine2@*:
    dependencies:
      prettier: "*"
  multishift@*:
    dependencies:
      "@remirror/pm": "*"
  node-fetch@*:
    dependencies:
      encoding: "*"
  pg@*:
    dependencies:
      pg-native: "*"
  postgraphile@^4.9.0:
    dependencies:
      "@graphile-contrib/pg-simplify-inflector": "*"
      postgraphile-plugin-connection-filter: "*"
    peerDependencies:
      graphql: ">=0.9 <0.14 || ^14.0.2"
  redis-parser@*:
    dependencies:
      hiredis: "*"
  relay-compiler@*:
    dependencies:
      relay-compiler-language-typescript: "*"
      relay-config: "*"
  typescript@*:
    dependencies:
      source-map-support: "*"
  y-protocols@*:
    dependencies:
      yjs: ^13.5.24

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
